#!/usr/bin/env python3

import gaffer

g = gaffer.Gaffer("http://localhost:8080")
# g.use_cert()

op1 = g.get_all(entities=["ip"], edges=["ipflow"])
op2 = g.limit(30)
ops = g.operation_chain([op1, op2])

res = g.execute(ops)

for v in res:
    if "resource" in v:
        print("Edge:", v["source"], "->", v["destination"])

    if "vertex" in v:
        print("Node:", v["vertex"])

